### ISSUE TITLE
Disable screen capture during use of application

### ISSUE THREAD

**Issue by whaber** [covidwatchorg/covidwatch-android-en#145]
Starting with Android 5.0, Google introduced the android.media.projection API which allows any third-party App to perform screen capture and screen sharing (https://developer.android.com/about/versions/android-5.0.html).
Such an App can capture everything on the device’s screen, including sensitive activity from all other Apps such as password keystrokes, credit card data, etc. The capturing ability remains on even if the user terminates/closes the App, but not after a reboot.

Protect all sensitive windows within the App by enabling the FLAG_SECURE flag. This flag will prevent Apps from being able to record the protected windows. Also, the flag will prevent users from taking screenshots of these windows (by pressing the VOLUME_DOWN and POWER buttons). As such screenshots are stored on the SDCard by default, they are accessible to all Apps and sensitive data may be exposed.
Secure Code
```
// Secure code for protecting one Activity
public class SecureActivity extends Activity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        
        // Set the Secure flag for this Window
        getWindow().setFlags(LayoutParams.FLAG_SECURE, LayoutParams.FLAG_SECURE);
    }
}
```

However, if the developers want to protect all the screens of their applications from third-party screen capturing and sharing, they need to use this flag in each of the Activities separately. There is no global mechanism to set this flag for all the screens at once. But, one can design their applications in such a way that the FLAG_SECURE needs to be used only once. Below is the code snippet:

Define a BaseActivity and set the FLAG_SECURE in that Activity :
```

> public class BaseActivity extends Activity {
> 
>     @Override
>     protected void onCreate(Bundle savedInstanceState) {
>         super.onCreate(savedInstanceState);
>         /**
>          * approach 1: create a base activity and set the FLAG_SECURE in it,
>          * Extend all other activities, Fragments from this activity
>          */
>         getWindow().setFlags(LayoutParams.FLAG_SECURE,
>                 LayoutParams.FLAG_SECURE);
>     }
> 

```
Use this BaseActivity as the superclass for all the other Activities.

```
public class LoginActivity extends BaseActivity
public class MainActivity extends BaseActivity

```

**Comment by Apisov** [comment]
@whaber Are you aware of [this ](https://commonsware.com/blog/2016/06/06/psa-flag-secure-window-leaks.html) issue and this [solution](https://github.com/commonsguy/cwac-security/blob/master/docs/FLAGSECURE.md)to it?
In short, `FLAG_SECURE` doesn't work for dialogs and other pop-ups views that originated from the screen that uses `FLAG_SECURE`. 

In our cases we don't have any sensitive data in dialogs or that sort of views but I believe it is important note to consider in your future recommendations about `FLAG_SECURE`.

**Comment by whaber** [comment]
@Apisov Thanks for the heads up.  As long as we aren't allowing screen capture when sensitive data is displayed, the primary risk is reduced.

If we are going to display sensitive data in dialogs and pop-ups in the future, we should weigh the risks of doing so (vs using other ways to display data).
