### ISSUE TITLE
Update target build to 30

### ISSUE THREAD

**Issue by Apisov** [covidwatchorg/covidwatch-android-en#154]
- [ ] Review changes in the API 30
- [ ] See if we need to add any changes
- [ ] Apply the changes if needed
- [ ] Test the app

**Comment by rasprague** [comment]
reviewed changes from API v29 to v30 (https://developer.android.com/about/versions/11/features and https://developer.android.com/sdk/api_diff/30/changes)

we're not using any of the changed methods / fields, neither are we using any new deprecations

v30 security changes don't affect bluetooth or internet permissions; we're already not using location permissions
