### ISSUE TITLE
Can't get past the permission screen

### ISSUE THREAD

**Issue by crayne** [covidwatchorg/covidwatch-android-en#7]
I build from develop.  When I get to the permission screen I see this:
![image](https://user-images.githubusercontent.com/134657/81366777-797ff580-90b9-11ea-844b-84b9f6ad79c6.png)
When I click on "Location Access On" it takes me to the settings for the app, where it says that no permissions are needed. Since I can't set the location permission, I cannot proceed.

**Comment by nkumarcc** [comment]
As UI/UX is about to get overhauled, this issue is definitely going to be deprecated. If a similar issue repeats with the new UX, let's reopen
