### ISSUE TITLE
Cannot enable exposure notifications on Google Pixel 1

### ISSUE THREAD

**Issue by dlines2008** [covidwatchorg/covidwatch-android-en#95]
Info from ZD ticket:

I cannot enable exposure notifications on my phone (Google Pixel 1), however, in settings it shows that it is showing notifications. When I click on enable exposure notifications, it shows a "something went wrong" prompt.

This issue arose after I installed the app. At the end of the setup process, I was unable to tap on the enable exposure notifications button. When I did tap on the button, a "something went wrong prompt" appears.

Note: I have asked the user which version of Android OS they are using and will add that info here when I have it.

![3c884950-ef72-4132-96aa-5ce17cb501d2-hs_file_upload-Screenshot_20200626-150213](https://user-images.githubusercontent.com/52087640/85930512-01e57000-b88b-11ea-9850-5fedce9d0efc.png)

**Comment by Apisov** [comment]
It might be useful to have a link to the original ZD ticket. 
One quick question: is the test account was added and the user gave some time to sync(from 5 to 30 minutes)?
